#!/bin/bash

# Autostart
pkill -x pipewire
pipewire &

pkill -x waybar
waybar &

# Settings
riverctl xcursor-theme Adwaita
riverctl focus-follows-cursor normal

# Displays
wlr-randr --output eDP-1 --scale 1.5

# Input
touchpad="pointer-2362-628-PIXA3854:00_093A:0274_Touchpad"

riverctl input $touchpad tap enabled
riverctl input $touchpad natural-scroll enabled
riverctl input $touchpad click-method clickfinger

# Mappings
riverctl map normal Super Q close
riverctl map normal Super+Shift E exit

riverctl map normal Super D spawn fuzzel
riverctl map normal Super Return spawn foot
riverctl map normal Super W spawn qutebrowser

# fuzzel

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Space to bump the focused view to the top of the layout stack
riverctl map normal Super Space zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Alt H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Alt L send-layout-cmd rivertile "main-count -1"

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Alt+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Alt $i toggle-focused-tags $tags

    # Super+Shift+Alt+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Alt $i toggle-view-tags $tags
done

# Super+Space to toggle float
riverctl map normal Super+Shift Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Volume
riverctl map -repeat normal None XF86AudioRaiseVolume spawn 'wpctl set-volume --limit 1 @DEFAULT_AUDIO_SINK@ 0.05+'
riverctl map -repeat normal None XF86AudioLowerVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-'
riverctl map normal None XF86AudioMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

# Brightness
riverctl map -repeat normal None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
riverctl map -repeat normal None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

# Colors
riverctl background-color 0x000000
riverctl border-color-focused 0xFFFFFF
riverctl border-color-unfocused 0x808080

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.5 &
