$terminal = foot
$drun = tofi-drun --drun-launch=true
$browser = librewolf -p

exec-once = hyprpaper

env = hyprcursor_size,20
env = xcursor_size,20

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2
    resize_on_border = false

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 5
}

dwindle {
    preserve_split = true
    force_split = 2
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    middle_click_paste = false
}

input:touchpad {
    disable_while_typing = false
    natural_scroll = true
}

$mainMod = super

binde = , xf86audioraisevolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%+ && notify-send "$(wpctl get-volume @DEFAULT_SINK@)"
binde = , xf86audiolowervolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%- && notify-send "$(wpctl get-volume @DEFAULT_SINK@)"
bind = , xf86audiomute, exec, wpctl set-mute @DEFAULT_SINK@ toggle && notify-send "$(wpctl get-volume @DEFAULT_SINK@)"

binde = , xf86monbrightnessup, exec, brightnessctl set +5% && notify-send "$(brightnessctl -m | awk -F, '{print $4}')" 
binde = , xf86monbrightnessdown, exec, brightnessctl set 5%- && notify-send "$(brightnessctl -m | awk -F, '{print $4}')" 

bind = $mainMod, b, exec, notify-send "$(acpi -b)"
bind = $mainMod, t, exec, notify-send "$(date +"%a, %b %d %l:%m %p")"

bind = $mainMod, return, exec, $terminal
bind = $mainMod, d, exec, $drun
bind = $mainMod, w, exec, $browser Personal
bind = $mainMod, e, exec, $browser School
bind = $mainMod shift, w, exec, $browser Personal --private-window
bind = $mainMod shift, e, exec, $browser School --private-window

bind = $mainMod, q, killactive
bind = $mainMod shift, q, exit
bind = $mainMod, f, fullscreen

bind = $mainMod, space, togglesplit

bind = $mainMod, h, movefocus, l
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u
bind = $mainMod, l, movefocus, r

bind = $mainMod shift, h, movewindow, l
bind = $mainMod shift, j, movewindow, d
bind = $mainMod shift, k, movewindow, u
bind = $mainMod shift, l, movewindow, r

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod shift, 1, movetoworkspace, 1
bind = $mainMod shift, 2, movetoworkspace, 2
bind = $mainMod shift, 3, movetoworkspace, 3
bind = $mainMod shift, 4, movetoworkspace, 4
bind = $mainMod shift, 5, movetoworkspace, 5
bind = $mainMod shift, 6, movetoworkspace, 6
bind = $mainMod shift, 7, movetoworkspace, 7
bind = $mainMod shift, 8, movetoworkspace, 8
bind = $mainMod shift, 9, movetoworkspace, 9
bind = $mainMod shift, 0, movetoworkspace, 10

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

windowrulev2 = suppressevent maximize, class:.*
