[ids]
*

include colemak-dh

[global]
default_layout = default

[main]
capslock = overload(control, esc)
leftmeta = leftalt
leftalt = leftmeta

[shift]
capslock = capslock

[default:layout]

[control+shift]
` = setlayout(colemak-dh)
