[font]
normal = { family = "JetBrainsMonoNerdFontMono", style = "normal" }
bold = { family = "JetBrainsMonoNerdFontMono", style = "bold" }
italic = { family = "JetBrainsMonoNerdFontMono", style = "italic" }
size = 20
